### ISSUE TITLE
Error compiling Less stylesheet

### ISSUE THREAD

**Issue by claudio-silva** [timjroberts/typescript-atomizer#11]
I had to comment 2 lines on `typescript-tooltip.less` to make it work without errors, altough the visual style gets degraded. It seems the required file is missing?

``` less
@import 'ui-variables';
//@import "tooltips";

.typescript-tooltip
{
    //.tooltip .tooltip-inner;
```

I'm using Atom 0.179.0 and typescript-atomizer 0.3.1

**Comment by timjroberts** [comment]
Hmm, that's an interesting one. The `tooltips` import is an Atom provided import just like the `ui-variables` reference. I'll take a look into it. Thanks @claudio-silva. Which OS are using by the way?

**Comment by claudio-silva** [comment]
I'm sorry for having bothered you with this, for it seems that  it's not a problem with your code.
I've finally found what was causing this. I was using a UI them for Atom that was not the default one. I guess the problem was being caused by that theme.
Thanks for your prompt response, though.
